import { auth } from '@/lib/auth'
import { NextResponse } from 'next/server'

export async function GET(req: Request) {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  if (session.user.role !== 'PROVIDER' && session.user.role !== 'ADMIN') {
    return NextResponse.json({ error: 'Provider only' }, { status: 403 })
  }

  const { searchParams } = new URL(req.url)
  const modelsParam = searchParams.get('models') ?? 'phi3:mini'
  const serverUrl = searchParams.get('server') ?? 'http://localhost:8080'
  const gpu = searchParams.get('gpu') ?? 'cpu'
  const hasNvidia = gpu !== 'cpu'
  // Validate URL scheme
  try {
    const parsed = new URL(serverUrl)
    if (!['http:', 'https:'].includes(parsed.protocol)) {
      return NextResponse.json({ error: 'Invalid server URL scheme' }, { status: 400 })
    }
  } catch {
    return NextResponse.json({ error: 'Invalid server URL' }, { status: 400 })
  }

  const modelIds = modelsParam.split(',').filter(Boolean)
  if (modelIds.length === 0 || modelIds.length > 8) {
    return NextResponse.json({ error: 'Invalid model count (1-8)' }, { status: 400 })
  }

  const lines: string[] = []
  lines.push('# Generated by Enigma Network')
  lines.push(`# Provider: ${session.user.email}`)
  lines.push(`# GPU: ${gpu}`)
  lines.push(`# Models: ${modelIds.join(', ')}`)
  lines.push('')
  lines.push('services:')

  const volumes: string[] = []
  const seen: Record<string, number> = {}

  for (const modelId of modelIds) {
    seen[modelId] = (seen[modelId] ?? 0) + 1
    const count = seen[modelId]
    const safeName = modelId.replace(/[^a-z0-9]/g, '-')
    const suffix = count > 1 ? `-${count}` : ''
    const ollamaService = `ollama-${safeName}${suffix}`
    const nodeService = `enigma-node-${safeName}${suffix}`
    const volName = `${ollamaService}-data`
    volumes.push(volName)

    lines.push(`  ${ollamaService}:`)
    lines.push(`    image: ollama/ollama`)
    if (hasNvidia) {
      lines.push(`    runtime: nvidia`)
      lines.push(`    environment:`)
      lines.push(`      - NVIDIA_VISIBLE_DEVICES=all`)
    }
    lines.push(`    # No ports exposed — Ollama only accessible internally by enigma-node`)
    lines.push(`    volumes:`)
    lines.push(`      - ${volName}:/root/.ollama`)
    lines.push(`    restart: unless-stopped`)
    lines.push(``)

    lines.push(`  ${nodeService}:`)
    lines.push(`    image: ghcr.io/enigma-network/enigma-node:latest`)
    lines.push(`    command:`)
    lines.push(`      - "-server"`)
    lines.push(`      - "${serverUrl}"`)
    lines.push(`      - "-backend"`)
    lines.push(`      - "ollama"`)
    lines.push(`      - "-backend-addr"`)
    lines.push(`      - "${ollamaService}:11434"`)
    lines.push(`    depends_on:`)
    lines.push(`      - ${ollamaService}`)
    lines.push(`    restart: unless-stopped`)
    lines.push(``)
  }

  lines.push('volumes:')
  volumes.forEach(v => lines.push(`  ${v}:`))
  lines.push('')

  return new Response(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/yaml',
      'Content-Disposition': 'attachment; filename="docker-compose.yml"',
    },
  })
}
